### ISSUE TITLE
Failed tests leaving running jupyter servers behind

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#176]
With a recent deploy, two servers for the catalyst-cooperative hub were started but never deleted. The test is marked as failed, with the following error:

```
Starting hub catalyst-cooperative health validation...
Running simple.ipynb test notebook...
Hub check health validation failed 2 times, hub not healthy.
Hub catalyst-cooperative not healthy! Stopping further deployments. Exception was jupyterhub server creation timeout=60 [s].
------------------------------ Captured log call -------------------------------
ERROR    jupyterhub_client.api:api.py:82 jupyterhub server creation timeout=60 [s]
INFO     backoff:_common.py:86 Backing off check_hub_health(...) for 1.0s (TimeoutError: jupyterhub server creation timeout=60 [s])
ERROR    jupyterhub_client.api:api.py:82 jupyterhub server creation timeout=60 [s]
ERROR    backoff:_common.py:101 Giving up check_hub_health(...) after 2 tries (TimeoutError: jupyterhub server creation timeout=60 [s])
```

It looks like `jupyterhub_client` might have a hardcoded 60s timeout for starting new servers. If this timeout is exceeded, then the test is marked as failing. In this case, it looks like pulling the image took about 2minutes, causing the whole server start process to take more than 3min:

```
$ k -n catalyst-cooperative describe pod jupyter-service-2dhub-2dhealth-2d30223b22-2d8095-2d43f6-2d9649-2de759e84c8033   
```
```
  Type    Reason     Age   From                                 Message
  ----    ------     ----  ----                                 -------
  Normal  Scheduled  19m   catalyst-cooperative-user-scheduler  Successfully assigned catalyst-cooperative/jupyter-service-2dhub-2dhealth-2d30223b22-2d8095-2d43f6-2d9649-2de759e84c8033 to gke-low-touch-hubs-c-user-pool-2020-0-3721ff18-7fsl
  Normal  Pulling    19m   kubelet                              Pulling image "us-central1-docker.pkg.dev/two-eye-two-see/low-touch-hubs/base-user:4066a62"
  Normal  Pulled     16m   kubelet                              Successfully pulled image "us-central1-docker.pkg.dev/two-eye-two-see/low-touch-hubs/base-user:4066a62"
  Normal  Created    16m   kubelet                              Created container notebook

```
But the servers are still running.

```
jupyter-service-2dhub-2dhealth-2d30223b22-2d8095-2d43f6-2d9649-2de759e84c8033   1/1     Running   0          15m
jupyter-service-2dhub-2dhealth-2de87c7697-2d3900-2d4077-2dbea9-2db86bf94aa438   1/1     
```

**Comment by yuvipanda** [comment]
They also leave user accounts behind

<img width="334" alt="image" src="https://user-images.githubusercontent.com/30430/105158672-3fb22a80-5b34-11eb-928a-04d95d0c8ec1.png">

**Comment by GeorgianaElena** [comment]
I believe this happened because the [`jupyterhub_client.execute_code()`](https://github.com/costrouc/jupyterhub_client/blob/master/jupyterhub_client/execute.py#L45) function doesn't cleanup the resources that it creates, in case of failure.

We solved this issue in the stress tester by re-writing the function with a bunch of try - finally statements (ref: https://github.com/utoronto-2i2c/jupyterhub-deploy/pull/60)

I can think of 3 approaches we could take to solve this issue:
- Do the same as in the stress tester, i.e. don't call directly `execute_notebook` (that calls `execute_code`) but instead re-write the function with try - finally statements.
- Implement this cleanup functionality in the upstream `jupyterhub_client` repo.
- Move the stress tester in its own repo and use that for hub health checks, instead of directly using the `jupterhub_client` repo.

@yuvipanda, what are your thoughts about this?

**Comment by yuvipanda** [comment]
> Implement this cleanup functionality in the upstream `jupyterhub_client` repo.

This is probably the way to go.  In general, moving as many things as possible upstream is <3

Thanks for diving into this, @GeorgianaElena!

**Comment by zaneselvans** [comment]
Ah yeah I was wondering what was up with those service accounts piling up!

**Comment by yuvipanda** [comment]
I think this has been fixed, right?

**Comment by GeorgianaElena** [comment]
It should be, yes! :+1:
