### ISSUE TITLE
Document our quay.io account

### ISSUE THREAD

**Issue by yuvipanda** [2i2c-org/pilot-hubs#210]
I want to use quay.io for user images built externally - like for [paleohack](https://quay.io/repository/2i2c/paleohack-2021). This is easier than putting things in our google cloud project, since we aren't paying for it :D Plus it can be made fully public. It also has fewer rate limits than dockerhub.

We can use the repo2docker github action to make PRs like https://github.com/LinkedEarth/paleoHackathon/pull/2. The images will auto build & push on each 

- [x] Give @GeorgianaElena access to this 2i2c quay.org account
- [x] Setup paleohack hub to use image built in https://quay.io/repository/2i2c/paleohack-2021
- [ ] Document the quay account at https://quay.io/organization/2i2c and how other 2i2c team members can access it

**Comment by choldgraf** [comment]
We should also provide some kind of documentation so that others can prepare their repositories for this workflow without requiring us to take action. For example, in watching the Paleo setup:

- Users need to set secrets for their repository, we should have instructions for how to do this
- Users need a brief primer on what Quay is and why we're using it
- Anything else?

I think ideally we want to get to a place where a user can show up on day 1 and say "Hey, I'd like you to give me a JupyterHub and I've followed your instructions and have a repository over here set up so that it'll push to `quay` like you described"

**Comment by yuvipanda** [comment]
Agree re: docs. I think we should add a section to https://github.com/jupyterhub/repo2docker-action#push-image-to-a-registry-other-than-dockerhub on how to push to quay.io, and then ask people to just do that. Nothing specific to us.

**Comment by choldgraf** [comment]
@yuvipanda who is the person that has access to the quay.io account? I'm trying to figure out what's next here.

- Is it something that others need to create an account for? In which case we should add this to our onboarding checklist
- Or something where we need to share a password? In which case, we should document who has the password and how to get it

**Comment by yuvipanda** [comment]
I've already added it to the onboarding checklist - https://github.com/2i2c-org/team-compass/pull/112. Is this something that can be closed now?

**Comment by choldgraf** [comment]
ah nice! yep let's close it :-)
