### ISSUE TITLE
Create a shared folder for each hub

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#29]
In Slack @yuvipanda mentioned wanting to create a shared folder each hub. This would be `read/write` for hub administrators, and `read-only` for hub non-admins. It would be used as a kind-of "distribution folder" so admins can put stuff there that users all have access to.

We may also want to explore ways to let *non-admins* deposit things in a shared folder (e.g. for collaboration or sharing work). @yuvipanda mentioned that we might be able to use Jitsi for this.

**Comment by yuvipanda** [comment]
We do this in Berkeley's [data100hub](https://github.com/berkeley-dsep-infra/datahub/blob/staging/deployments/data100/config/common.yaml#L20).
We mount the shared dir readonly for everyone, and mount an extra readwrite version just for admins. This would be for providing
common datasets - maybe we can just call it 'datasets' instead of the more generic 'shared'?

Separate from this should be a way for users to collaborate with each other. I started working 
on [jupyterhub-shared-volumes](https://github.com/yuvipanda/jupyterhub-shared-volumes) for this earlier,
but never finished it.

**Comment by yuvipanda** [comment]
This is now done! All hubs now have a 'shared' directory in their home that's readonly. Admins will see a 'shared-readwrite' directory, which is exactly the same - but mounted read-write. This should help them put common materials there for access to the other users.

**Comment by choldgraf** [comment]
wohoo! and now documented as well :-) https://2i2c.org/pilot/administrators.html#share-data-and-files-across-users
