### ISSUE TITLE
Scoping machine sizes for node pools or use auto-provisioning

### ISSUE THREAD

**Issue by sgibson91** [2i2c-org/pilot-hubs#666]
### Description

While working on #661 and creating the machine profiles for the Pangeo hub, I tried to match nodepool machine sizes with the resources offered by each profile. Here are the profiles:

https://github.com/sgibson91/pilot-hubs/blob/f6d8cfa673ebad7c399e5ddb2b98f12b7c33b65c/config/hubs/pangeo-hubs.cluster.yaml#L81-L119

And the machine sizes I'm suggesting for each nodepool:

https://github.com/sgibson91/pilot-hubs/blob/f6d8cfa673ebad7c399e5ddb2b98f12b7c33b65c/terraform/gcp/projects/pangeo-hubs.tfvars#L13-L39

I was quite pleased with myself until I realised that this probably means 1 pod per machine in the nodepool and this probably isn't the best optimisation.

I then asked what machines are being used on the old cluster, but it seems they might be using [auto-provisioning](https://cloud.google.com/kubernetes-engine/docs/how-to/node-auto-provisioning) (https://github.com/2i2c-org/pilot-hubs/issues/661#issuecomment-915413357) which means that GKE automatically handles creating new nodepools and assigns a machine size according to workload.

So my questions for discussion are:

1. Is auto-provisioning something we should consider supporting?
2. If the answer to 1 is "No" or "Not right now", how should I go about scoping the machine sizes for the Pangeo cluster? Any recommendations based on the above linked profile list?

### Value / benefit

I will benefit from discussion around this and making a confident choice

**Comment by yuvipanda** [comment]
I played with auto-provisioning a while ago, and found that we needed to tune our memory requests anyway to not get a lot of wasted resources. I remember asking for a pod with 6G of RAM (say) but it'll provision a node with 10G of RAM. The other 4G will be wasted for the most part. I'm sure there's more to this, and I didn't dig into it enough. 

Using autoprovisioning will definitely make our life *much* simpler in the long run, so we should evaluate how we can best make use of it. Without it, we'll have to do terraform changes for each new user profile we create. It'll cut our work by half.

I think the bigger question is 'how many pods per node do we aim for?'. In an educational context, it makes sense to pack as many pods into a node as possible, to overprovision memory for them. We can give everyone a 1G limit and still pack 100 pods into a node with 64G of RAM by giving them a 256M guarantee, relying on the fact that it is unlikely that all 100 of them will go over the 1G limit at the same time. Here is a heatmap of memory use data from a hub I run, with ~1000 students. It has 256M guarantee and 1G limit:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/30430/132667302-9e1fe418-3546-48c3-93fe-d0d844269d3d.png">

I'm sure there's some way to statistically figure out ideal guarantee and limit based on this distribution, maximizing the number of pods that can be put on a node. But from trial and error, 256M guarantee + 1G limit on n1-highmem-8 instances seemed right.

It also helps a lot with performance - one new node coming up can support 100 students, so the median wait time is much reduced. 

For research use cases, we might not want to overprovision at all, and set guarantee and limit to be the same. When someone asks for 8G of RAM, we assume they will in fact use all that 8G of RAM. Assuming this is true (I am pretty sure people always ask for more resources than they need!), the overprovisioning advantage disappears. Then putting multiple pods on a node is only helpful to reduce node spinup time. In that case, we have to trade that off with resources lying around unused - we might bring up a 64G node but only 16G of it will be used, so we end up paying for all those extra resources that are not needed...

Perhaps the way to deal with this is to collect more data in the long run? I feel like with educational contexts, having access to user data on actual resource usage vs provided limits / guarantees has helped guide node size. Maybe we should explicitly determine what data can be useful for that in a research context, and collect that to make this decision?

**Comment by yuvipanda** [comment]
As a next step, my suggestion is to put in a timeboxed task for evaluating autoprovisioner to see if we can mimic the config that the current pangeo hub has. That gives us a clear completion criteria, and then we can use that to collect data on making better decisions in the future

**Comment by sgibson91** [comment]
> It'll cut our work by half.

This sounds appealing! 😆 

> Perhaps the way to deal with this is to collect more data in the long run?

@TomAugspurger has any data been collected on the current Pangeo cluster that we can learn from?

> my suggestion is to put in a timeboxed task for evaluating autoprovisioner to see if we can mimic the config that the current pangeo hub has

Agree, but I don't think "before Ryan's class starts" is a big enough timebox for such a deep dive. So I think we should track this issue in https://github.com/orgs/2i2c-org/projects/16 and just pick a set of sensible machines for now.

**Comment by TomAugspurger** [comment]
It looks like the grafana deployments for the two hubs are in bad shape :(

http://grafana.aws-uswest2.pangeo.io/grafana/, http://grafana.us-central1-b.gcp.pangeo.io/grafana/?orgId=1. I dunno if the GCP one has data and it's just the UI that's broken. And the GCP console might have more, I'm not sure.

**Comment by sgibson91** [comment]
Here's my proposal for machines

### Small pool
Minimum resources:
- 1 GB
- 0.3 CPU
Maximum resources:
- 4 GB
- 2 CPU

Assuming N=50 (where N is our pods/node) this would scale to:

Minimum resources:
- 50 GB
- 15 CPU
Maximum resources:
- 200 GB
- 100 CPU

**Recommendation:** `n1-standard-16` which has 16 CPU and 60 GB

### Medium pool
Minimum resources:
- 4 GB
- 1 CPU
Maximum resources:
- 8 GB
- 2 CPU

Assuming N=25 this would scale to:

Minimum resources:
- 100 GB
- 25 CPU
Maximum resources:
- 200 GB
- 50 CPU

**Recommendation:** `n1-standard-32` which has 32 CPUs and 120 GB

### Large and ML pool
Minimum resources:
- 12 GB (same for ML)
- 1 CPU (same for ML)
Maximum resources:
- 16 GB (same for ML)
- 4 CPU (2 CPU for ML)

Assuming N=10 this would scale to:

Minimum resources:
- 120 GB (same for ML)
- 10 CPU (same for ML)
Maximum resources:
- 160 GB (same for ML)
- 40 CPU (20 CPU for ML)

**Recommendation:** `n1-highmem-16` which has 16 CPUs and 104 GB

**Comment by sgibson91** [comment]
@rabernat does the above sound sensible for your course?

**Comment by choldgraf** [comment]
just a quick note that https://github.com/2i2c-org/pilot-hubs/issues/666#issuecomment-915956414 and the surrounding conversation in this issue would almost already be copy/pasteable into a pretty interesting blog post :-)

**Comment by rabernat** [comment]
Wow these tables are great! Such a useful summary of the choices.

However, I have to admit that I don't really feel informed enough to be approving this level of detail about the node pools. I'll do my best to give some useful feedback though...

When looking at these numbers, I am focusing most on memory, which tends to be the biggest constraint for our workloads. My impression is that you are proposing fairly large-sized nodes. For the Medium pool, we will be running a fairly large ` n1-standard-32` node (120 GB) basically all the time. So I wonder, what if there are only a few people working overnight?--there would be lots wasted resources if notebook pods are just requesting 16 GB.

As the grant PI ultimately responsible for the budget, _I feel like I would need price information in order to really make an informed decision._ Maybe it's not a big deal to just leave a few big nodes running all the time. Or maybe it will overspend our budget. My instinct would be to go for smaller nodes. **Do we have the ability to put rough monthly cost numbers on the table?**

Perhaps I'm spoiled from the GCS autoprovisioning we currently have set up. I never really had to think much about this before. So I'm fine to just go with whatever you all think is best, look at the costs, and adjust as needed.

> has any data been collected on the current Pangeo cluster that we can learn from?

I totally agree it would also be super useful to bring in logs from our existing cluster. Unfortunately we have no reliable reporting system for such logs. I have some one-off scripts that scraped stackdriver logs which I made two years ago, but they are probably not runnable now. So I basically don't know our current usage rates 🤦 . That's another thing I hope 2i2c will change about our setup 😄 .

Finally, do we have to make similar choices for the Dask Gateway nodepools? Do those share nodepools with the Jupyter nodes? Do they use preemptible instances? This is particularly thorny because gateway users can request a wide range of memory per worker.

**Comment by sgibson91** [comment]
> My impression is that you are proposing fairly large-sized nodes.

We can reduce the size of the nodes if you think that's appropriate and see how we go. That is a non-destructive update if we change our minds later down the road.

> Do we have the ability to put rough monthly cost numbers on the table?

I will update the tables with number from here: https://cloud.google.com/compute/all-pricing

> Perhaps I'm spoiled from the GCS autoprovisioning we currently have set up.

I wonder if we should bite the bullet and just enable autoprovisioning now instead, and use your classes to collect data and answer the q's @yuvipanda raised. I was trying to avoid this option so close to your class since it is a _destructive_ change - the cluster will be deleted/replaced and the hub will need to be reinstalled. (Compared to changed the nodepools, which changes them in place and is therefore less destructive.) But perhaps it's better to do that now rather than later when some home dirs will be populated.

**Comment by choldgraf** [comment]
I don't think I have the right technical background to really understand the implications, but my intuition in reading this is that we should try and set up autoprovisioning, but only if we don't think that it has a high chance of creating a fire that @sgibson91 feels compelled to put out. 

From reading above, it seems like autoprovisioning will require less human intervention and be more performant and stable from a users perspective, with the potential drawback that it is more costly or inefficient. Because we have a healthy amount of credits, this makes me think we can prioritize learning and saving human time over cost optimization *right now*. In the long run we obviously want to minimize costs as well, but it feels like this is something we can do over time.

So what about

- turn on auto provisioning for these hubs
- create an issue where we list out the major questions we'd like to answer as we learn about how this choice affects the infrastructure 
- time box that issue to revisit and write up thoughts in, say, 2 months 
- decide then whether to continue this experiment or if we've learned enough we can just make a decision one way or another

**Comment by sgibson91** [comment]
> I was trying to avoid this option so close to your class since it is a _destructive_ change

Amazingly, terraform is telling me this _isn't_ a destructive change! The cluster can be updated in place!

**Comment by rabernat** [comment]
That's great!

Since we don't want to do preemptible nodes for notebook pods (yes for Dask pods), it looks like the base operating cost (assuming none of the pools scale to zero) would be around $1600 / month. That's fine to start, but we should look for ways to optimize down the road. A key factor is the scale-up time. If the nodepools can scale up in 1-2 minutes, it's not problem using smaller nodes. If it's more like 10 minutes, that becomes a major drag.



> it seems like autoprovisioning will require less human intervention and be more performant and stable from a users perspective, with the potential drawback that it is more costly or inefficient.

Chris can you say more about why it might be "costly and inefficient"? My impression was that autoprovisioning would tune the node requests to the kubernetes pod resource requests, thereby being _more_ efficient.

I am fine with whatever choice the tech team feels is right here. Chris is right that we are not pinching pennies at this stage. As long as we have the metrics and process to continuously optimize costs, that is what is important.

**Comment by sgibson91** [comment]
I like Chris's proposal (echoing Yuvi) of running a time-boxed experiment with auto-provisioning and evaluating performance, cost-benefits, etc at the end of the time-box. I'm working on a PR to enable node auto-provisioning on the Pangeo cluster now.

**Comment by rabernat** [comment]
> All node pools scale to zero

They _can_ scale to zero. But we should probably assume that at least one user will be logged on at all times.

**Comment by sgibson91** [comment]
I opened #670 to enable node auto-provisioning if someone from @2i2c-org/tech-team could review!

**Comment by choldgraf** [comment]
Just a quick response for @rabernat 

> Chris can you say more about why it might be "costly and inefficient"?

My reasoning here is just based on Yuvi's sentence here:

> I played with auto-provisioning a while ago, and found that we needed to tune our memory requests anyway to not get a lot of wasted resources. I remember asking for a pod with 6G of RAM (say) but it'll provision a node with 10G of RAM. The other 4G will be wasted for the most part. I'm sure there's more to this, and I didn't dig into it enough.

I took that to mean "non-optimized auto provisioning might mean that we unnecessarily ask for resources that we don't use, like getting a 10GB node that has a pod with a min RAM of 6GB.

**Comment by sgibson91** [comment]
Once #670 is merged, I opened https://github.com/2i2c-org/pilot-hubs/issues/671 to track the time-boxed experiment

**Comment by damianavila** [comment]
> I like Chris's proposal (echoing Yuvi) of running a time-boxed experiment with auto-provisioning and evaluating performance, cost-benefits, etc at the end of the time-box.

I agree with this!

In general, I have been more familiarized with "manual" provisioning so eager to know how auto-provisioning is behaving in this scenario. It would be definitely less work, and it "should be" more efficient... we would need to check for that.

> just a quick note that #666 (comment) and the surrounding conversation in this issue would almost already be copy/pasteable into a pretty interesting blog post :-)

The differentiation @yuvipanda is doing when he talks about educational vs research and how the provisioning model works on different scenarios is key, IMHO. And a blog post about this would be awesome for the community :wink:
