### ISSUE TITLE
Document whether / how user data is backed up

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#67]
Some folks have asked questions like "should I tell my students to create backups of their work in case their data gets lost?" What should I respond in those cases? Does our NFS server have backups set up? If not, should we recommend people download `.zip`s of their files occasionally? Have we ever had an issue where we lost user storage data?

**Comment by yuvipanda** [comment]
We now do 7day daily 'disaster recovery' backups. However, I think this isn't good enough, since we don't wanna do a lot of work restoring this - especially for recovering a single user's work.

I think we should:

1. Make it easy and obvious for a student to download their entire home directory
2. Make it possible for an admin to get the home directory of all students.

**Comment by choldgraf** [comment]
I'm gonna close this one and we can track it in https://github.com/2i2c-org/pilot-hubs/issues/641
