### ISSUE TITLE
Add a page for logging on with invalid credentials

### ISSUE THREAD

**Issue by choldgraf** [2i2c-org/pilot-hubs#70]
@ericvd-ucb just mentioned that if you try to log in but you don't have correct credentials, you get a kind-of confusing page about Auth0 that has @yuvipanda's name on it. We should try to make this show up as a page w/ more information for users.

**Comment by yuvipanda** [comment]
@choldgraf this is tied to #14 I think.

However, this was due to a misconfiguration of the hubs themselves - the spelman hub existed in both pilot. and cloudbank. for a while, and our deploy code wasn't set up for this. Hopefully this shouldn't be a thing that happens often.

There #46 for the issue when users are trying to login without being already added.

**Comment by yuvipanda** [comment]
https://github.com/2i2c-org/pilot-hubs/commit/66511da368e420506955f342550598799b0c71c6 now fixes the issue that threw up this issue in the first place.

**Comment by choldgraf** [comment]
Just checked this - so the page is definitely better in that it's a JupyterHub page, but it is currently a blank `403 hidden` page:

![image](https://user-images.githubusercontent.com/1839645/96164261-d6d16b80-0ecf-11eb-9db2-03ee8a05fec1.png)

is there a way that we can customize this to serve our own 403 template? I feel like it would be helpful to include information like "If you were just logging in, check that your email address has been added to the list of users for this hub, and if not contact your administrator to be added."

**Comment by yuvipanda** [comment]
@choldgraf yep, that's tracked in https://github.com/2i2c-org/pilot-hubs/issues/46
